version: '1.0'
stages:
  - "clone"
steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "cb-seenivasan/eks-installer"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: master
    git: "cb-seenivasan"
    stage: "clone"

  check_env:
    title: Check environment for required variables
    image: bash:4.4.23
    commands:
      - echo 'Checking for CLUSTER_NAME, AWS_ACCESS_KEY_ID, and AWS_SECRET_ACCESS_KEY...'
      - bash -c '[[ -z $CLUSTER_NAME || -z $AWS_ACCESS_KEY_ID || -z $AWS_SECRET_ACCESS_KEY ]] && exit 1 || true'
      - cf_export K8S_NAME="eks-$CLUSTER_NAME"

  load_tfstate:
    title: Attempt to load Terraform statefile from Codefresh context
    image: codefresh/cli:0.8.54
    commands:
      - apk add --update make bash
      - ls -lrt
      - sh scripts/codefresh-load-tfstate.sh || echo "Skipping."

  setup_eks_cluster:
    title: Setup EKS cluster using Terraform
    image: hashicorp/terraform:0.11.7
    commands:
      - apk add --update make bash
      - set +e; sh scripts/setup.sh; cf_export RC=$?

  save_tfstate:
    title: Save Terraform statefile to Codefresh context
    image: codefresh/cli:0.8.54
    commands:
      - apk add --update make bash
      - sh scripts/codefresh-save-tfstate.sh
      - exit ${{RC}}

  create_kubernetes_resources:
    title: Create additional Kubernetes resources
    image: lachlanevenson/k8s-kubectl:v1.10.4
    commands:
      - rm -f heptio-authenticator-aws
      - wget https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-06-05/bin/linux/amd64/heptio-authenticator-aws
      - chmod +x heptio-authenticator-aws
      - cp heptio-authenticator-aws /usr/local/bin
      - export KUBECONFIG="$(pwd)/kubernetes/kubeconfig.yaml"
      - cd kubernetes/
      - kubectl apply -f config-map-aws-auth.yaml
      - kubectl apply -f service-account.yaml
      - kubectl apply -f role-binding.yaml

  init_helm:
    title: Initialiaze Helm in the cluster
    image: lachlanevenson/k8s-helm:v2.9.1
    commands:
      - cp heptio-authenticator-aws /usr/local/bin
      - export KUBECONFIG="$(pwd)/kubernetes/kubeconfig.yaml"
      - helm init --service-account admin-user

  get_token:
    title: Extract token from Kubernetes secret
    image: lachlanevenson/k8s-kubectl:v1.10.4
    commands:
      - cp heptio-authenticator-aws /usr/local/bin
      - export KUBECONFIG="$(pwd)/kubernetes/kubeconfig.yaml"
      - export SECRET_ID="$(kubectl -n kube-system get secret | grep admin-user | awk '{print $1}')"
      - cf_export K8S_TOKEN=$(kubectl -n kube-system get secret $SECRET_ID -o jsonpath='{.data.token}')

  add_cluster:
    title: Add EKS cluster to Codefresh account
    image: byrnedo/alpine-curl:0.1.5
    commands:
      - apk add --update make bash jq
      - export K8S_CA="$(cat kubernetes/kubeca.txt)"
      - export K8S_HOST="$(cat kubernetes/kubehost.txt)"
      - ./scripts/codefresh-add-cluster.sh
